name: FE CI/CD
on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push FE image
        env:
          IMAGE: ghcr.io/${{ github.repository_owner }}/total_app_fe:latest
        run: |
          docker build -t "$IMAGE" 
          docker push "$IMAGE"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          [ -n "${{ secrets.SSH_KNOWN_HOSTS }}" ] && echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts || true

      - name: Deploy FE on server
        run: |
          SSH_OPTS="-o StrictHostKeyChecking=no"; [ -f ~/.ssh/known_hosts ] && SSH_OPTS=""
          ssh -i ~/.ssh/id_rsa $SSH_OPTS ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            'cd /srv/total_app && docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} && docker compose pull web && docker compose up -d web'
